### ISSUE TITLE
Update the examples to import everything from `merlin`

### ISSUE THREAD

**Issue by benfred** [NVIDIA-Merlin/Merlin#115]

**Comment by mikemckiernan** [comment]
@benfred , does this change apply to all repositories in the NVIDIA-Merlin organization?  If yes, does the change go live in the `main` branch immediately or does it need to wait until the next release?

**Comment by karlhigley** [comment]
I think it should be okay to create a PR that updates the example notebooks, since AFAIK `merlin-core`, `merlin-models`, and `nvtabular` are all now exporting their contents under the `merlin` namespace. We might want to wait to merge it until closer to the next release to keep the examples runnable on the previous release though.

(`nvtabular` is currently `merlin.transform`, which is potentially subject to change but likely what we'll move forward with.)

**Comment by viswa-nvidia** [comment]
This affects all the examples

**Comment by karlhigley** [comment]
Having made an attempt, I don't think is actually reasonable to do without some rework to the text of the NVT examples, which is out of scope for this release. However, I will open a PR that updates the exports in `merlin.transforms` to smooth the path for doing this in a future release.
