### ISSUE TITLE
[BUG] cudf---User defined functions are currently not supported on Series 

### ISSUE THREAD

**Issue by WonderingWJ** [NVIDIA-Merlin/Merlin#160]
The code is as below:
```
df_total['shift_timestamp'] = df_total.groupby('passenger_id')['bubble_timestamp'].shift(1).to_arrow()
def kernel(bubble_timestamp,shift_timestamp, second_diff,):
    for i, (x, y) in enumerate(zip(bubble_timestamp, shift_timestamp)):
            second_diff[i] = x-y
df_total=df_total.apply_rows(kernel
                        ,incols=["bubble_timestamp","shift_timestamp"]
                        ,outcols=dict(second_diff=np.int64)
                        ,kwargs={}
                       )
df_total['second_diff'].fillna(0, inplace=True)
```

In docker image `nvcr.io/nvidia/merlin/merlin-training:22.03`,  we will run into the error message `TypeError: User defined functions are currently not supported on Series with dtypes str and category`.
But in docker image  `nvcr.io/nvidia/merlin/merlin-training:21.12`, the code can be successfully run.

**Comment by karlhigley** [comment]
@albert17 This sounds like it might be a version or dependency with the containers. Could you take a look when you get a chance?

**Comment by viswa-nvidia** [comment]
@karlhigley , is this a blocker ?

**Comment by viswa-nvidia** [comment]
This will need help from the cudf team

**Comment by rjzamora** [comment]
@WonderingWJ - Ideally this issue would be filed in cudf, rather than Merlin. However, we can probably get to the bottom of this pretty fast (and ping the relevant cudf devs for help if not) if you can provide [a full minimal reproducer](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).  It seems likely that your problem has to do with some change in the interaction between cudf and pyarrow, but the behavior clearly depends on the actual data you have in `'bubble_timestamp'`.
