### ISSUE TITLE
[BUG] LambdaOp must be explicit

### ISSUE THREAD

**Issue by mattf** [NVIDIA-Merlin/Merlin#163]
https://github.com/NVIDIA-Merlin/Merlin/blob/main/examples/getting-started-movielens/02-ETL-with-NVTabular.ipynb

```
ratings = nvt.ColumnGroup(["rating"]) >> (lambda col: (col > 3).astype("int8"))
```
this code will result in an exception when trying to call `create_node` on a `function`

a fix is to explicitly use `LambdaOp`-
```
ratings = nvt.ColumnGroup(["rating"]) >> nvt.ops.LambdaOp(lambda col: (col > 3).astype("int8"))
```

a better fix would be to type detect the function and wrap it with a LambdaOp

**Comment by karlhigley** [comment]
I believe the functionality to allow unwrapped lambdas was intentionally deprecated and removed in order to support multiple types of graphs and nodes. It looks like the examples in the Merlin repo haven't been updated in a while though; the version of the same notebook in the NVTabular repo does use an explicit `LamdaOp`. Seems like the path forward here to might be to migrate the examples from the NVTabular repo to the Merlin repo. What do you think, @rnyak?

**Comment by mattf** [comment]
it looks like https://github.com/NVIDIA-Merlin/Merlin/tree/main/examples/getting-started-movielens is stale compared to https://github.com/NVIDIA-Merlin/NVTabular/tree/main/examples/getting-started-movielens

if you ask me, i'll say to move the NVTabular version over to the Merlin repository. it's more discoverable and natural.
