### ISSUE TITLE
[DOC] Update references docs based on latest 3 containers  (Merlin - HCTR/TF/PYT)

### ISSUE THREAD

**Issue by viswa-nvidia** [NVIDIA-Merlin/Merlin#377]
## Report needed documentation

We've changed from 6 containers to 3 containers. 
https://nvidia.slack.com/archives/C0365QKG5JS/p1654701319137629
Documentation needs to be updated so that the references to old container structure are updated

**Comment by mikemckiernan** [comment]
I'll start with the simplest changes that I believe we need to make:
* The [Merlin Containers](https://nvidia-merlin.github.io/Merlin/main/containers.html) page needs to reflect that we have only three containers and no separation for training vs inference.
* Because this is a significant change, I'd like the the 22.06 instance of the page to acknowledge the change from 22.05 and offer a link to the v0.7.1 doc because I assume we have an audience for the recent containers.
* (Small hiccup--I need to push a v0.7.1-docs branch with the current content. Not a biggie.)
* Update the [Support Matrix](https://nvidia-merlin.github.io/Merlin/main/support_matrix/index.html) page similarly--revise so that we only show 3 containers, acknowledge in text the change to a combined container, and offer a link to the v0.7.1 doc.

I can be persuaded if there are other suggestions.

**Comment by mikemckiernan** [comment]
NVTabular repo: https://github.com/NVIDIA-Merlin/NVTabular/pull/1581
