### ISSUE TITLE
Change T4Rec library to expect scalar features to be 1D ibrary to expect scalar features and /list feature to be a dict instead of tuple

### ISSUE THREAD

**Issue by viswa-nvidia** [NVIDIA-Merlin/Merlin#820]

**Comment by viswa-nvidia** [comment]
@gabrielspmoreira , comment and close this ticket

**Comment by gabrielspmoreira** [comment]
I am closing this ticket because Transformers4Rec was not affect by dataloader changes because:
- T4Rec sets [sparse_as_dense=True](https://github.com/NVIDIA-Merlin/Transformers4Rec/blob/8dfee74db03733bf2737493e6f3ee174d8dbecfa/transformers4rec/torch/utils/data_utils.py#L308) for dataloader so that it returns a 2D dense padded dense tensor and not a ragged representation.
- T4Rec was already automatically squeezing the last dim of scalar input features, which were previously 2D. Now they are 1D, but that doesn't cause an error on squeeze as it does in TF
