### ISSUE TITLE
[QST] why the cardinality in the schema is +1 of all the unique entries in my original data?

### ISSUE THREAD

**Issue by Tselmeg-C** [NVIDIA-Merlin/Merlin#861]
# ❓ Questions & Help

## Details

![image](https://user-images.githubusercontent.com/64394100/226314372-041b903b-f449-499c-99bb-bd893c29e70a.png)

I am trying to understand why the cardinality in the schema is +1 of all the unique entries in my original data? Does it has sth to deal with 'code-start' problem? encoding any 'unkonw'/'None' into a seperate token? Because in my original data, I have considered this and added an extra row with 'unknown' for each column. If the NV Tabular transform is API is already considering this, should I do this change to my original data?

**Comment by oliverholworthy** [comment]
Hi @Tselmeg-C , yes this is because the NVTabular Categorify transformation reserves the zeroth value to encode [missing (NA)](https://docs.rapids.ai/api/cudf/stable/user_guide/missing-data.html) and values that were not seen during the workflow fit stage. Example below:

```python
import cudf
import nvtabular as nvt
from merlin.io import Dataset

workflow = nvt.Workflow(["col"] >> nvt.ops.Categorify())

fit_dataset = Dataset(cudf.DataFrame({"col": [None, "a", "b", "c"]}))
workflow.fit_transform(fit_dataset).compute()
# =>
#    col
# 0    0
# 1    1
# 2    2
# 3    3

transform_dataset = Dataset(cudf.DataFrame({"col": [None, "unseen-during-fit"]}))
workflow.transform(transform_dataset).compute()
# =>
#    col
# 0    0
# 1    0
```

If you set your 'unknown' values to NA in the columns of your dataframe then the Categorify transformation in NVTabular will encode these as '0'.

**Comment by Tselmeg-C** [comment]
@oliverholworthy Thank you very much!
